### ISSUE TITLE
The auto inject causes my game to instantly crash

### ISSUE THREAD

**Issue by T1KK** [subjoel/SirSubUI#1]
When I launch roblox with the ui open, my game instantly crashes. I know it's because of the auto inject since i've tried launching it with roblox already open and it can execute scripts perfectly fine

**Comment by subjoel** [comment]
Do you use the V1 or V2 release? Also I'm soon updating it when the dll gets updated.

**Comment by T1KK** [comment]
i'm using the V2 release, also thanks for replying

**Comment by subjoel** [comment]
@T1KK i updated the ui, fixed all bugs including auto inject and made it significally less in size, 11mb instead of 350mb
